# Generated by Django 2.2 on 2022-10-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_store', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('married', models.BooleanField(default=False)),
            ],
        ),
    ]
