# Generated by Django 2.2.28 on 2022-10-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actioncheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
