# Generated by Django 2.2 on 2022-11-09 11:32

from django.db import migrations, models
from django

class Migration(migrations.Migration):

    dependencies = [
        ('actioncheck', '0002_test1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
