# Generated by Django 2.2 on 2022-11-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actioncheck', '0003_test1_age'),
    ]

    operations = [
    ]
