# Generated by Django 2.2.28 on 2022-11-03 13:00

from django.db import migrations

TARGET_APP = 'oauth2_provider'

class Migration(migrations.Migration):

    def __init__(self, name, app_label):
        super(Migration, self).__init__(name, TARGET_APP)

    run_before = [
    ]
    dependencies = [
        ('oauth2_provider', '0001_initial'),
        ('oauth2_provider', '0002_auto_20190406_1805'),
        ('oauth2_provider', '0003_auto_20201211_1314'),
        ('oauth2_provider', '0004_auto_20200902_2022'),
        ('oauth2_provider', '0005_auto_20211222_2352'),
        ('oauth2_provider', '0006_alter_application_client_secret'),
        ('actioncheck', '0003_test1_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='Grant'
        ),
        migrations.DeleteModel(
            name='RefreshToken'
        )
    ]
